name: C++ Build CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2 (GCC/g++)
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc

    - name: Build Application
      shell: cmd
      run: |
        if not exist build mkdir build
        g++ -std=c++20 -w -O2 src/main.cpp -I include -L lib -lraylib -lglfw3dll -lSUIutils -o build/main.exe

    - name: Copy Assets and Dependencies
      shell: cmd
      run: |
        xcopy /y /d "bin\*.dll" "build\"
        xcopy /y /e "Fonts" "build\Fonts"
        xcopy /y /e "textures" "build\textures"
        xcopy /y /e "simpleUI Shaders" "build\simpleUI Shaders"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/